Included validation for source path argument

diff --git a/libs/utils b/libs/utils
--- a/libs/utils
+++ b/libs/utils
@@ -2,7 +2,10 @@
 
 # Validating the file or DIR exists and not repearinf twice or more in the arg
 validate_path() {
-    if [[ -d $1 ]]; then
+    if [[ -z "$1" ]]; then
+        eval ./zkomp --help
+        exit 1
+    elif [[ -d $1 ]]; then
         return 0 # 0 = true
     elif [[ -f $1 ]]; then
         return 0 # 0 = true
@@ -25,8 +28,30 @@ spinner() {
         for i in "${spin[@]}"
         do
             echo -ne "\b$i"
-            sleep 0.05
+            sleep 0.08
         done
     done
     echo -ne "\n"
+}
+
+extract_file() {
+    if [ -f $1 ] ; then
+        case $1 in
+        *.tar.bz2) tar xjf $1 &;;
+        *.tar.gz) tar xzf $1 &;;
+        *.bz2) bunzip2 $1 &;;
+        *.rar) rar x $1 &;;
+        *.gz) gunzip $1 &;;
+        *.tar) tar xf $1 &;;
+        *.tbz2) tar xjf $1 &;;
+        *.tgz) tar xzf $1 &;;
+        *.zip) unzip $1 &;;
+        *.Z) uncompress $1 &;;
+        *.7z) 7z x $1 &;;
+        *.iso) 7z x $1 -h &;;
+        *) echo "'$1' cannot be extracted via zkomp" ;;
+        esac
+    else
+        echo "'$1' is not a valid file"
+    fi
 }
